Sprint3
ClevertecFrontendLab/Irina-coud pull request #1
Opened 2023-02-16 15:21 UTC by Irina-coud

2023-02-16 15:25 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 50%.
Общее количество тестов: 4.
Количество непройденных тестов: 2.
***
**Get books test -- ErrorBookId -- bookId-error (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina-coud/1676561122/Get%20books%20test%20--%20ErrorBookId%20--%20bookId-error%20(failed).png)
***
**Get books test -- getSuccessBookId -- bookId-success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina-coud/1676561122/Get%20books%20test%20--%20getSuccessBookId%20--%20bookId-success%20(failed).png)
***
**app-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina-coud/1676561122/app-sucess.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina-coud/1676561122/bookId-loading.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina-coud/1676561122/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina-coud/1676561122/main-loading.png)

2023-02-16 15:38 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 4.
Количество непройденных тестов: 0.
***
**app-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina-coud/1676561893/app-sucess.png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina-coud/1676561893/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina-coud/1676561893/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina-coud/1676561893/bookId-sucess.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina-coud/1676561893/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina-coud/1676561893/main-loading.png)

2023-02-16 16:13 UTC, vvikota requested changes

2023-02-16 16:13 UTC, vvikota commented on .editorconfig
> +insert_final_newline = true
![image](https://user-images.githubusercontent.com/30027067/219420126-920586af-f7e8-4fca-8435-b2266f357f12.png)
когда ошибка запроса то нужно отображать алерт с текстом "что то пошло не так", лоадер нужно выключать в таком случае

2023-02-16 16:13 UTC, vvikota commented on .editorconfig
> +charset = utf-8
картинки книжек из папки img можно удалять, теперь они приходят с сервера

2023-02-16 16:13 UTC, vvikota commented on src/store/store.ts
> +// function getState() {
все что закоментано нужно удалить если не используется

2023-02-16 22:02 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 4.
Количество непройденных тестов: 0.
***
**app-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina-coud/1676584955/app-sucess.png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina-coud/1676584955/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina-coud/1676584955/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina-coud/1676584955/bookId-sucess.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina-coud/1676584955/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina-coud/1676584955/main-loading.png)

2023-02-17 06:52 UTC, vvikota requested changes

2023-02-17 06:52 UTC, vvikota commented on .editorconfig
> +trim_trailing_whitespace = true
еще одна правка)
![image](https://user-images.githubusercontent.com/30027067/219570569-ddf5a7b3-3daa-48d0-bd1d-4376cda79bf7.png)
в этом спринте с сервера уже приходит значение рейтинга и нужно его отображать, если пришло например значение 3 то закрашиваем 3 звездочки и две остаются пустыми, аналогично и на детальной странице книги.

2023-02-17 18:36 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 4.
Количество непройденных тестов: 0.
***
**app-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina-coud/1676658975/app-sucess.png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina-coud/1676658975/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina-coud/1676658975/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina-coud/1676658975/bookId-sucess.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina-coud/1676658975/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina-coud/1676658975/main-loading.png)

2023-02-17 18:40 UTC, vvikota approved these changes

2023-02-17 18:57 UTC, merged