Sprint4
ClevertecFrontendLab/Irina-coud pull request #2
Opened 2023-02-22 23:10 UTC by Irina-coud

2023-02-22 23:16 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 16.
Количество непройденных тестов: 0.
***
**active-category-programming.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina-coud/1677107772/active-category-programming.png)
***
**clearing-search-input.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina-coud/1677107772/clearing-search-input.png)
***
**empty-category.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina-coud/1677107772/empty-category.png)
***
**find-books.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina-coud/1677107772/find-books.png)
***
**search-result-not-found.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina-coud/1677107772/search-result-not-found.png)

2023-02-23 06:42 UTC, Ivan6813 requested changes

2023-02-23 06:42 UTC, Ivan6813 commented on src/components/burger/burger.tsx
> +                  dispatch(changeCurrentCategory(item.name))
эти же действия повторяются с 89 по 92 строку, можно вынести это наверх в одну функцию, что бы не дублировать

2023-02-23 06:42 UTC, Ivan6813 commented on src/components/burger/burger.tsx
>    const location = useLocation();
nit: по аналогии как и с useParams ты сделала, можно и тут деструктуризацией достать  
`const { pathname } = useLocation();`

2023-02-23 06:42 UTC, Ivan6813 commented on src/components/empty-search/empty-search.tsx
> +  </EmptyFilteredBooksWrapper>
а может сделать один компонент на это дело? 🤔 Там выше у тебя есть EmptyFilteredBooks и он такой же, можно пропсами прокинуть текст и data-test-id

2023-02-23 06:42 UTC, Ivan6813 commented on src/components/navigate/navigate.tsx
> +          {booksCategories.map((item: any) => (
уверен здесь можно обойтись без any и задать нормальный тип

2023-02-23 06:42 UTC, Ivan6813 commented on src/pages/books-list/books-container/book-card/book-card.tsx
> +      {filteredBooks.length !== 0 ? (filteredBooks.map((card) => (
можно обойтись просто filteredBooks.length, ведь если длинна будет положительная, то это true, а если ноль, то будет false

2023-02-23 06:42 UTC, Ivan6813 commented on src/utils/use-filters.ts
> +  const sortBooks = [...cards].sort((a: IBook, b: IBook): any => {
подумай как можно сделать это без any

2023-02-23 08:24 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 81%.
Общее количество тестов: 16.
Количество непройденных тестов: 3.
***
**active-category-programming.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina-coud/1677140670/active-category-programming.png)
***
**bread crumbs -- desktop -- transfer from all books category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina-coud/1677140670/bread%20crumbs%20--%20desktop%20--%20transfer%20from%20all%20books%20category%20to%20book%20page%20(failed).png)
***
**bread crumbs -- desktop -- transfer from programming category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina-coud/1677140670/bread%20crumbs%20--%20desktop%20--%20transfer%20from%20programming%20category%20to%20book%20page%20(failed).png)
***
**bread crumbs -- tablet -- transfer from all books category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina-coud/1677140670/bread%20crumbs%20--%20tablet%20--%20transfer%20from%20all%20books%20category%20to%20book%20page%20(failed).png)
***
**clearing-search-input.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina-coud/1677140670/clearing-search-input.png)
***
**empty-category.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina-coud/1677140670/empty-category.png)
***
**find-books.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina-coud/1677140670/find-books.png)
***
**search-result-not-found.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina-coud/1677140670/search-result-not-found.png)

2023-02-23 09:00 UTC, Ivan6813 requested changes

2023-02-23 09:35 UTC, Irina-coud commented on src/components/burger/burger.tsx
> +              onClick={(event) => handlerClickCategory(event)}
попробовала ваш вариант, выскакивает ошибка линта, загуглив которую, предлгают в jsx элементах использовать стрелочные функции.
оставила стрелочный вариант, если это плохое решение - напишите.

2023-02-23 10:32 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 50%.
Общее количество тестов: 16.
Количество непройденных тестов: 8.

2023-02-23 11:04 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 16.
Количество непройденных тестов: 0.
***
**active-category-programming.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina-coud/1677150272/active-category-programming.png)
***
**clearing-search-input.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina-coud/1677150272/clearing-search-input.png)
***
**empty-category.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina-coud/1677150272/empty-category.png)
***
**find-books.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina-coud/1677150272/find-books.png)
***
**search-result-not-found.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina-coud/1677150272/search-result-not-found.png)

2023-02-23 11:18 UTC, merged